CREATE TABLE `CAR` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `BRAND` VARCHAR(50),
  `LINE` VARCHAR(50),
  `PLATE_CAR` VARCHAR(50),
  `STATUS` VARCHAR(50),
  CONSTRAINT PK_CAR PRIMARY KEY(ID)
);

CREATE TABLE `CLIENT` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `DOCUMENT_TYPE` VARCHAR(5) NOT NULL,
  `DOCUMENT_NUMBER` VARCHAR(30) NOT NULL,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `PHONE_NUMBER` VARCHAR(20) NOT NULL,
  `ADDRESS` VARCHAR(100) NOT NULL,
  CONSTRAINT PK_CLIENT PRIMARY KEY(ID)
);

CREATE TABLE RENT (
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CLIENT_ID` INTEGER NOT NULL,
    `CAR_ID` INTEGER NOT NULL,
    `RENT_DATE` DATE NOT NULL,
    `DAYS` INTEGER NOT NULL,
    CONSTRAINT PK_RENT PRIMARY KEY(ID),
    CONSTRAINT FK_RENT_CAR FOREIGN KEY (CAR_ID) REFERENCES CAR(ID),
    CONSTRAINT FK_RENT_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);